

const GET_ALL_DOGS = "GET_ALL_DOGS";
const GET_TEMPERAMENTS = "GET_TEMPERAMENTS";
const GET_DOG_BY_NAME = "GET_DOG_BY_NAME";
const GET_DETAIL = 'GET_DETAIL'
const POST_DOG = 'POST_DOG'
const FILTER_TEMPERAMENTS = "FILTER_TEMPERAMENTS";
const FILTER_NAME = "FILTER_NAME";
const FILTER_ORIGIN_DATA = "FILTER_ORIGIN_DATA";
const FILTER_WEIGHT = "FILTER_WEIGHT"

module.exports={
   
   GET_ALL_DOGS,
   GET_TEMPERAMENTS,
   GET_DOG_BY_NAME,
   GET_DETAIL,
   POST_DOG,
   FILTER_TEMPERAMENTS,
   FILTER_NAME,
   FILTER_ORIGIN_DATA,
   FILTER_WEIGHT

}